package cert

import (
	"ALLinSSL/backend/public"
	"fmt"
	"strconv"
	"strings"
	"time"
)

func GetSqlite() (*public.Sqlite, error) {
	s, err := public.NewSqlite("data/data.db", "")
	if err != nil {
		return nil, err
	}
	s.TableName = "cert"
	return s, nil
}

// getWorkflowsBySha256s returns all workflows, used to compute workflow_refs per cert.
func getWorkflowsBySha256s() ([]map[string]any, error) {
	s, err := public.NewSqlite("data/data.db", "")
	if err != nil {
		return nil, err
	}
	s.TableName = "workflow"
	defer s.Close()
	return s.Where("1=1", []interface{}{}).Select()
}

func GetList(search string, p, limit, status int64) ([]map[string]any, int, error) {
	var data []map[string]any
	var count int64
	s, err := GetSqlite()
	if err != nil {
		return data, 0, err
	}
	defer s.Close()

	var limits []int64
	if p >= 0 && limit >= 0 {
		limits = []int64{0, limit}
		if p > 1 {
			limits[0] = (p - 1) * limit
			limits[1] = limit
		}
	}

	// 获取当前时间
	now := time.Now()
	// 转换为字符串格式
	nowStr := now.Format("2006-01-02 15:04:05")
	// 30 天后的时间
	nowPlus30Days := now.AddDate(0, 0, 30)
	nowPlus30DaysStr := nowPlus30Days.Format("2006-01-02 15:04:05")

	filterSql := "1=1 "
	// status: -1 已过期 0/其它 全部 1 即将过期 2 正常
	if status == -1 {
		filterSql += "and end_time <= '" + nowStr + "'"
	} else if status == 1 {
		filterSql += "and end_time > '" + nowStr + "' AND end_time <= '" + nowPlus30DaysStr + "'"
	} else if status == 2 {
		filterSql += "and end_time > '" + nowPlus30DaysStr + "'"
	}

	if search != "" {
		filterSql += "and domains like '%" + search + "%'"
	}
	count, err = s.Where(filterSql, []interface{}{}).Count()
	data, err = s.Where(filterSql, []interface{}{}).Order("end_time", "esc").Limit(limits).Select()

	if err != nil {
		return data, 0, err
	}
	for _, v := range data {
		endtime, err := time.Parse("2006-01-02 15:04:05", v["end_time"].(string))
		if err != nil {
			continue
		}
		v["end_day"] = strconv.FormatInt(int64(endtime.Sub(time.Now())/(24*time.Hour)), 10)
	}

	// For workflow_id matching, only the cert with the highest id per workflow
	// is considered actively associated; older certs generated by the same
	// workflow are historical and no longer in use.
	latestCertForWorkflow := map[string]int64{}
	if sc, err2 := GetSqlite(); err2 == nil {
		if all, err3 := sc.Field([]string{"id", "workflow_id"}).Where("workflow_id != '' AND workflow_id != 'null'", []interface{}{}).Select(); err3 == nil {
			for _, c := range all {
				wfid := fmt.Sprintf("%v", c["workflow_id"])
				if wfid == "" || wfid == "<nil>" {
					continue
				}
				var cid int64
				switch v := c["id"].(type) {
				case int64:
					cid = v
				case int:
					cid = int64(v)
				}
				if prev, ok := latestCertForWorkflow[wfid]; !ok || cid > prev {
					latestCertForWorkflow[wfid] = cid
				}
			}
		}
		sc.Close()
	}

	// Attach workflow_refs to each cert
	workflows, _ := getWorkflowsBySha256s()
	for i, c := range data {
		sha, _ := c["sha256"].(string)
		wfId := fmt.Sprintf("%v", c["workflow_id"])
		var certId int64
		switch v := c["id"].(type) {
		case int64:
			certId = v
		case int:
			certId = int64(v)
		}
		var refs []map[string]string
		seen := map[string]bool{}
		for _, w := range workflows {
			wid := fmt.Sprintf("%v", w["id"])
			wname, _ := w["name"].(string)
			wcontent, _ := w["content"].(string)
			if seen[wid] {
				continue
			}
			isLatestForWorkflow := wfId != "" && wfId != "<nil>" && wfId == wid && certId == latestCertForWorkflow[wfId]
			if isLatestForWorkflow || (sha != "" && strings.Contains(wcontent, sha)) {
				refs = append(refs, map[string]string{"id": wid, "name": wname})
				seen[wid] = true
			}
		}
		if refs == nil {
			refs = []map[string]string{}
		}
		data[i]["workflow_refs"] = refs
	}

	return data, int(count), nil
}

func AddCert(source, key, cert, issuer, issuerCert, domains, sha256, historyId, startTime, endTime, endDay string) error {
	s, err := GetSqlite()
	if err != nil {
		return err
	}
	defer s.Close()
	workflowId := ""
	if historyId != "" {
		s, err := public.NewSqlite("data/data.db", "")
		if err != nil {
			return err
		}
		s.TableName = "workflow_history"
		defer s.Close()
		// 查询 workflowId
		wh, err := s.Where("id=?", []interface{}{historyId}).Select()
		if err != nil {
			return err
		}
		if len(wh) > 0 {
			workflowId = wh[0]["workflow_id"].(string)
		}
	}

	now := time.Now().Format("2006-01-02 15:04:05")
	_, err = s.Insert(map[string]any{
		"source":      source,
		"key":         key,
		"cert":        cert,
		"issuer":      issuer,
		"issuer_cert": issuerCert,
		"domains":     domains,
		"sha256":      sha256,
		"history_id":  historyId,
		"workflow_id": workflowId,
		"create_time": now,
		"update_time": now,
		"start_time":  startTime,
		"end_time":    endTime,
		"end_day":     endDay,
	})
	if err != nil {
		return err
	}
	return nil
}

func SaveCert(source, key, cert, issuerCert, historyId string) (string, error) {
	if err := public.ValidateSSLCertificate(cert, key); err != nil {
		return "", err
	}

	certObj, err := public.ParseCertificate([]byte(cert))
	if err != nil {
		return "", fmt.Errorf("解析证书失败: %v", err)
	}
	// SHA256
	sha256, err := public.GetSHA256(cert)
	if err != nil {
		return "", fmt.Errorf("获取 SHA256 失败: %v", err)
	}
	if d, _ := GetCert(sha256); d != nil {
		return sha256, nil
	}

	domainList := strings.Join(public.ExtractCertDomains(certObj), ",")

	// 提取 CA 名称（Issuer 的组织名）
	caName := "UNKNOWN"
	if len(certObj.Issuer.Organization) > 0 {
		caName = certObj.Issuer.Organization[0]
	} else if certObj.Issuer.CommonName != "" {
		caName = certObj.Issuer.CommonName
	}
	// 证书有效期
	startTime := certObj.NotBefore.Format("2006-01-02 15:04:05")
	endTime := certObj.NotAfter.Format("2006-01-02 15:04:05")
	endDay := fmt.Sprintf("%d", int(certObj.NotAfter.Sub(time.Now()).Hours()/24))

	err = AddCert(source, key, cert, caName, issuerCert, domainList, sha256, historyId, startTime, endTime, endDay)
	if err != nil {
		return "", fmt.Errorf("保存证书失败: %v", err)
	}
	return sha256, nil
}

// UpdateCert 更新一张手动上传（source=="upload"）的证书。
// 契约：返回 len(uncovered) > 0 且 err == nil 时，表示新证书域名未覆盖原证书域名，
// 证书「未写库」，需用户确认后带 force=true 重试；此时 newSha256 为空。
func UpdateCert(id, certPEM, keyPEM string, force bool) (oldSha256, newSha256 string, uncovered []string, err error) {
	if err = public.ValidateSSLCertificate(certPEM, keyPEM); err != nil {
		return
	}
	certObj, err := public.ParseCertificate([]byte(certPEM))
	if err != nil {
		err = fmt.Errorf("解析证书失败: %v", err)
		return
	}
	newSha256, err = public.GetSHA256(certPEM)
	if err != nil {
		err = fmt.Errorf("获取 SHA256 失败: %v", err)
		return
	}

	// 读取当前记录，校验 source 必须为 upload
	s, err := GetSqlite()
	if err != nil {
		return
	}
	defer s.Close()
	rows, err := s.Where("id=?", []interface{}{id}).Select()
	if err != nil || len(rows) == 0 {
		err = fmt.Errorf("证书不存在")
		return
	}
	if source, _ := rows[0]["source"].(string); source != "upload" {
		err = fmt.Errorf("仅支持编辑手动上传的证书")
		return
	}
	oldSha256, _ = rows[0]["sha256"].(string)

	// 解析新证书元数据
	domains := public.ExtractCertDomains(certObj)

	// 校验新证书域名是否覆盖原证书域名，未覆盖且未强制时提前返回（不做任何变更）。
	// 以重新解析旧证书 PEM 为准（真源），而非信任去规范化的 domains 缓存列；
	// 仅当旧证书缺失/解析失败时才回退到缓存列。
	if !force {
		var oldDomains []string
		if oldCertPEM, _ := rows[0]["cert"].(string); oldCertPEM != "" {
			if oldObj, e := public.ParseCertificate([]byte(oldCertPEM)); e == nil {
				oldDomains = public.ExtractCertDomains(oldObj)
			}
		}
		if oldDomains == nil {
			oldDomainsStr, _ := rows[0]["domains"].(string)
			oldDomains = strings.Split(oldDomainsStr, ",")
		}
		uncovered = public.UncoveredDomains(domains, oldDomains)
		if len(uncovered) > 0 {
			newSha256 = "" // 未写库，不返回 sha（契约见函数注释）
			return
		}
	}

	caName := "UNKNOWN"
	if len(certObj.Issuer.Organization) > 0 {
		caName = certObj.Issuer.Organization[0]
	} else if certObj.Issuer.CommonName != "" {
		caName = certObj.Issuer.CommonName
	}

	now := time.Now().Format("2006-01-02 15:04:05")
	_, err = s.Where("id=?", []interface{}{id}).Update(map[string]interface{}{
		"cert":        certPEM,
		"key":         keyPEM,
		"sha256":      newSha256,
		"domains":     strings.Join(domains, ","),
		"issuer":      caName,
		"start_time":  certObj.NotBefore.Format("2006-01-02 15:04:05"),
		"end_time":    certObj.NotAfter.Format("2006-01-02 15:04:05"),
		"end_day":     fmt.Sprintf("%d", int(certObj.NotAfter.Sub(time.Now()).Hours()/24)),
		"update_time": now,
	})
	if err != nil {
		return
	}

	// 把所有 workflow content 中的旧 sha256 替换为新 sha256
	if oldSha256 != "" && oldSha256 != newSha256 {
		ws, _ := getWorkflowsBySha256s()
		for _, w := range ws {
			content, _ := w["content"].(string)
			if !strings.Contains(content, oldSha256) {
				continue
			}
			newContent := strings.ReplaceAll(content, oldSha256, newSha256)
			wid := fmt.Sprintf("%v", w["id"])
			sw, e2 := public.NewSqlite("data/data.db", "")
			if e2 != nil {
				continue
			}
			sw.TableName = "workflow"
			sw.Where("id=?", []interface{}{wid}).Update(map[string]interface{}{"content": newContent})
			sw.Close()
		}
	}
	return
}

// GetWorkflowRefs returns workflows associated with a cert identified by its db id and sha256.
func GetWorkflowRefs(id, sha256 string) []map[string]string {
	s, err := GetSqlite()
	if err != nil {
		return []map[string]string{}
	}
	rows, err := s.Where("id=?", []interface{}{id}).Select()
	s.Close()
	if err != nil || len(rows) == 0 {
		return []map[string]string{}
	}
	wfId := fmt.Sprintf("%v", rows[0]["workflow_id"])

	// latest cert per workflow_id (same logic as GetList)
	latestCertForWorkflow := map[string]int64{}
	if sc, e2 := GetSqlite(); e2 == nil {
		if all, e3 := sc.Field([]string{"id", "workflow_id"}).Where("workflow_id != '' AND workflow_id != 'null'", []interface{}{}).Select(); e3 == nil {
			for _, c := range all {
				wfid := fmt.Sprintf("%v", c["workflow_id"])
				if wfid == "" || wfid == "<nil>" {
					continue
				}
				var cid int64
				switch v := c["id"].(type) {
				case int64:
					cid = v
				case int:
					cid = int64(v)
				}
				if prev, ok := latestCertForWorkflow[wfid]; !ok || cid > prev {
					latestCertForWorkflow[wfid] = cid
				}
			}
		}
		sc.Close()
	}
	var certId int64
	switch v := rows[0]["id"].(type) {
	case int64:
		certId = v
	case int:
		certId = int64(v)
	}

	workflows, _ := getWorkflowsBySha256s()
	var refs []map[string]string
	seen := map[string]bool{}
	for _, w := range workflows {
		wid := fmt.Sprintf("%v", w["id"])
		wname, _ := w["name"].(string)
		wcontent, _ := w["content"].(string)
		if seen[wid] {
			continue
		}
		isLatest := wfId != "" && wfId != "<nil>" && wfId == wid && certId == latestCertForWorkflow[wfId]
		if isLatest || (sha256 != "" && strings.Contains(wcontent, sha256)) {
			refs = append(refs, map[string]string{"id": wid, "name": wname})
			seen[wid] = true
		}
	}
	if refs == nil {
		return []map[string]string{}
	}
	return refs
}

func UploadCert(key, cert string) (string, error) {
	sha256, err := SaveCert("upload", key, cert, "", "")
	if err != nil {
		return sha256, fmt.Errorf("保存证书失败: %v", err)
	}
	return sha256, nil
}

func DelCert(id string) error {
	s, err := GetSqlite()
	if err != nil {
		return err
	}
	defer s.Close()

	_, err = s.Where("id in ("+id+")", []interface{}{}).Delete()
	if err != nil {
		return err
	}
	return nil
}

func GetCert(id string) (map[string]string, error) {
	s, err := GetSqlite()
	if err != nil {
		return nil, err
	}
	defer s.Close()

	res, err := s.Where("id=? or sha256=?", []interface{}{id, id}).Select()
	if err != nil {
		return nil, err
	}
	if len(res) == 0 {
		return nil, fmt.Errorf("证书不存在")
	}

	data := map[string]string{
		"domains": res[0]["domains"].(string),
		"cert":    res[0]["cert"].(string),
		"key":     res[0]["key"].(string),
	}

	return data, nil
}

// ========================================================
